----------------------------
-- Global Engine Textures --
----------------------------

F_ResourceFailedToLoadImagePath = "..\\engine\\images\\resources\\resourceFailedToLoad.png"

F_Textures = {
	-- Resources
	empty = "..\\engine\\images\\resources\\empty.png",
	-- Project Hub
	flatEngine = "..\\engine\\images\\engine\\FlatEngine.png",
	flatEngineLogo = "..\\engine\\images\\engine\\FlatEngineLogo.png",
	flatEngineLogoGradient = "..\\engine\\images\\engine\\FlatEngineLogoGradient.png",
	selectProject = "..\\engine\\images\\engine\\selectProject.png",
	projectHubBg = "..\\engine\\images\\engine\\projectHubBg.png",
	-- File Explorer
	cppFile = "..\\engine\\images\\fileTypes\\cpp.png",
	hFile = "..\\engine\\images\\fileTypes\\h.png",
	luaFile = "..\\engine\\images\\fileTypes\\lua.png",
	pngFile = "..\\engine\\images\\fileTypes\\png.png",
	folderFile = "..\\engine\\images\\fileTypes\\folder.png",
	mapFile = "..\\engine\\images\\fileTypes\\contextFile.png",
	sceneFile = "..\\engine\\images\\fileTypes\\sceneFile.png",
	projectFile = "..\\engine\\images\\fileTypes\\projectFile.png",
	animFile = "..\\engine\\images\\fileTypes\\animFile.png",
	audioFile = "..\\engine\\images\\fileTypes\\audioFile.png",
	unmarkedFile = "..\\engine\\images\\fileTypes\\file.png",
	tileSetFile = "..\\engine\\images\\fileTypes\\tileSetFile.png",
	prefabFile = "..\\engine\\images\\fileTypes\\prefabFile.png",
	-- Scene View
	translate = "..\\engine\\images\\icons\\translate.png",
	scale = "..\\engine\\images\\icons\\scale.png",
	rotate = "..\\engine\\images\\icons\\rotate.png",
	tileBrush = "..\\engine\\images\\icons\\tileBrush.png",
	transformArrow = "..\\engine\\images\\widgets\\transformArrow.png",
	transformArrowAllWhite = "..\\engine\\images\\widgets\\transformArrowAllWhite.png",
	transformArrowXWhite = "..\\engine\\images\\widgets\\transformArrowXWhite.png",
	transformArrowYWhite = "..\\engine\\images\\widgets\\transformArrowYWhite.png",
	camera = "..\\engine\\images\\icons\\camera.png",
	play = "..\\engine\\images\\icons\\play.png",
	pause = "..\\engine\\images\\icons\\pause.png",
	stop = "..\\engine\\images\\icons\\stop.png",
	nextFrame = "..\\engine\\images\\icons\\next.png",
	expand = "..\\engine\\images\\icons\\expand.png",
	expandFlipped = "..\\engine\\images\\icons\\collapse.png",
	trash = "..\\engine\\images\\icons\\delete.png",
	openFile = "..\\engine\\images\\icons\\open.png",
	newFile = "..\\engine\\images\\icons\\new.png",
	saveFile = "..\\engine\\images\\icons\\save.png",
	saveAsFile = "..\\engine\\images\\icons\\saveAs.png",
	keyFrame = "..\\engine\\images\\icons\\keyFrame.png",
	threeDots = "..\\engine\\images\\icons\\threeDots.png",
	show = "..\\engine\\images\\icons\\show.png",
	hide = "..\\engine\\images\\icons\\hide.png",
	prefabCube = "..\\engine\\images\\icons\\prefabCube.png",
	left = "..\\engine\\images\\icons\\left.png",
	right = "..\\engine\\images\\icons\\right.png",
	down = "..\\engine\\images\\icons\\down.png",
	up = "..\\engine\\images\\icons\\up.png",
	upLeft = "..\\engine\\images\\icons\\upLeft.png",
	upRight = "..\\engine\\images\\icons\\upRight.png",
	downLeft = "..\\engine\\images\\icons\\downLeft.png",
	downRight = "..\\engine\\images\\icons\\downRight.png",
	center = "..\\engine\\images\\icons\\center.png",
	upDirectory = "..\\engine\\images\\icons\\upDirectory.png",
	back = "..\\engine\\images\\icons\\back.png",
}